using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace TestServer.Controllers
{
    [Route("view")]
    public class ViewController : Controller
    {
        private static readonly List<string[]> Locales = new List<string[]> ()
        {
            new string[] { "Afghanistan", "AF", "AFG", "Pashto", "ps", "pus", "ps-AF" },
            new string[] { "Afghanistan", "AF", "AFG", "Dari", "prs", "prs", "prs-AF" },
            new string[] { "Albania", "AL", "ALB", "Albanian", "sq", "sqi", "sq-AL" },
            new string[] { "Algeria", "DZ", "DZA", "Arabic", "ar", "ara", "ar-DZ" },
            new string[] { "Argentina", "AR", "ARG", "Spanish", "es", "spa", "es-AR" },
            new string[] { "Armenia", "AM", "ARM", "Armenian", "hy", "hye", "hy-AM" },
            new string[] { "Australia", "AU", "AUS", "English", "en", "eng", "en-AU" },
            new string[] { "Austria", "AT", "AUT", "German", "de", "deu", "de-AT" },
            new string[] { "Bahrain", "BH", "BHR", "Arabic", "ar", "ara", "ar-BH" },
            new string[] { "Bangladesh", "BD", "BGD", "Bengali", "bn", "bng", "bn-BD" },
            new string[] { "Basque", "ES", "ESP", "Basque", "eu", "eus", "eu-ES" },
            new string[] { "Belarus", "BY", "BLR", "Belarusian", "be", "bel", "be-BY" },
            new string[] { "Belgium", "BE", "BEL", "French", "fr", "fra", "fr-BE" },
            new string[] { "Belgium", "BE", "BEL", "Dutch", "nl", "nld", "nl-BE" },
            new string[] { "Belize", "BZ", "BLZ", "English", "en", "eng", "en-BZ" },
            new string[] { "Bolivarian Republic of Venezuela", "VE", "VEN", "Spanish", "es", "spa", "es-VE" },
            new string[] { "Bolivia", "BO", "BOL", "Quechua", "quz", "qub", "quz-BO" },
            new string[] { "Bolivia", "BO", "BOL", "Spanish", "es", "spa", "es-BO" },
            new string[] { "Brazil", "BR", "BRA", "Portuguese", "pt", "por", "pt-BR" },
            new string[] { "Brunei Darussalam", "BN", "BRN", "Malay", "ms", "msa", "ms-BN" },
            new string[] { "Bulgaria", "BG", "BGR", "Bulgarian", "bg", "bul", "bg-BG" },
            new string[] { "Cambodia", "KH", "KHM", "Khmer", "km", "khm", "km-KH" },
            new string[] { "Canada", "CA", "CAN", "French", "fr", "fra", "fr-CA" },
            new string[] { "Canada", "CA", "CAN", "English", "en", "eng", "en-CA" },
            new string[] { "Caribbean", "29", "29", "English", "en", "eng", "en-029" },
            new string[] { "Catalan", "ES", "ESP", "Catalan", "ca", "cat", "ca-ES" },
            new string[] { "Chile", "CL", "CHL", "Mapudungun", "arn", "arn", "arn-CL" },
            new string[] { "Chile", "CL", "CHL", "Spanish", "es", "spa", "es-CL" },
            new string[] { "Colombia", "CO", "COL", "Spanish", "es", "spa", "es-CO" },
            new string[] { "Costa Rica", "CR", "CRI", "Spanish", "es", "spa", "es-CR" },
            new string[] { "Croatia", "HR", "HRV", "Croatian", "hr", "hrv", "hr-HR" },
            new string[] { "Cyrillic, Azerbaijan", "AZ", "AZE", "Azeri", "az", "aze", "az-Cyrl-AZ" },
            new string[] { "Cyrillic, Bosnia and Herzegovina", "BA", "BIH", "Serbian", "sr", "srn", "sr-Cyrl-BA" },
            new string[] { "Cyrillic, Bosnia and Herzegovina", "BA", "BIH", "Bosnian", "bs", "bsc", "bs-Cyrl-BA" },
            new string[] { "Cyrillic, Mongolia", "MN", "MNG", "Mongolian", "mn", "mon", "mn-MN" },
            new string[] { "Cyrillic, Montenegro", "ME", "MNE", "Serbian", "sr", "srp", "sr-Cyrl-ME" },
            new string[] { "Cyrillic, Serbia", "RS", "SRB", "Serbian", "sr", "srp", "sr-Cyrl-RS" },
            new string[] { "Cyrillic, Serbia and Montenegro (Former", "CS", "SCG", "Serbian )", "sr", "srp", "sr-Cyrl-CS" },
            new string[] { "Cyrillic, Tajikistan", "TJ", "TAJ", "Tajik", "tg", "tgk", "tg-Cyrl-TJ" },
            new string[] { "Cyrillic, Uzbekistan", "UZ", "UZB", "Uzbek", "uz", "uzb", "uz-Cyrl-UZ" },
            new string[] { "Czech Republic", "CZ", "CZE", "Czech", "cs", "ces", "cs-CZ" },
            new string[] { "Denmark", "DK", "DNK", "Danish", "da", "dan", "da-DK" },
            new string[] { "Dominican Republic", "DO", "DOM", "Spanish", "es", "spa", "es-DO" },
            new string[] { "Ecuador", "EC", "ECU", "Quechua", "quz", "que", "quz-EC" },
            new string[] { "Ecuador", "EC", "ECU", "Spanish", "es", "spa", "es-EC" },
            new string[] { "Egypt", "EG", "EGY", "Arabic", "ar", "ara", "ar-EG" },
            new string[] { "El Salvador", "SV", "SLV", "Spanish", "es", "spa", "es-SV" },
            new string[] { "Estonia", "EE", "EST", "Estonian", "et", "est", "et-EE" },
            new string[] { "Ethiopia", "ET", "ETH", "Amharic", "am", "amh", "am-ET" },
            new string[] { "Faroe Islands", "FO", "FRO", "Faroese", "fo", "fao", "fo-FO" },
            new string[] { "Finland", "FI", "FIN", "Finnish", "fi", "fin", "fi-FI" },
            new string[] { "Finland", "FI", "FIN", "Swedish", "sv", "swe", "sv-FI" },
            new string[] { "Finland", "FI", "FIN", "Sami, Northern", "se", "smg", "se-FI" },
            new string[] { "Finland", "FI", "FIN", "Sami, Skolt", "sms", "sms", "sms-FI" },
            new string[] { "Finland", "FI", "FIN", "Sami, Inari", "smn", "smn", "smn-FI" },
            new string[] { "Former Yugoslav Republic of Macedonia", "MK", "MKD", "Macedonian", "mk", "mkd", "mk-MK" },
            new string[] { "France", "FR", "FRA", "French", "fr", "fra", "fr-FR" },
            new string[] { "France", "FR", "FRA", "Breton", "br", "bre", "br-FR" },
            new string[] { "France", "FR", "FRA", "Occitan", "oc", "oci", "oc-FR" },
            new string[] { "France", "FR", "FRA", "Corsican", "co", "cos", "co-FR" },
            new string[] { "France", "FR", "FRA", "Alsatian", "gsw", "gsw", "gsw-FR" },
            new string[] { "Galician", "ES", "ESP", "Galician", "gl", "glg", "gl-ES" },
            new string[] { "Georgia", "GE", "GEO", "Georgian", "ka", "kat", "ka-GE" },
            new string[] { "Germany", "DE", "DEU", "German", "de", "deu", "de-DE" },
            new string[] { "Germany", "DE", "DEU", "Upper Sorbian", "hsb", "hsb", "hsb-DE" },
            new string[] { "Germany", "DE", "DEU", "Lower Sorbian", "dsb", "dsb", "dsb-DE" },
            new string[] { "Greece", "GR", "GRC", "Greek", "el", "ell", "el-GR" },
            new string[] { "Greenland", "GL", "GRL", "Greenlandic", "kl", "kal", "kl-GL" },
            new string[] { "Guatemala", "GT", "GTM", "K'iche", "qut", "qut", "qut-GT" },
            new string[] { "Guatemala", "GT", "GTM", "Spanish", "es", "spa", "es-GT" },
            new string[] { "Honduras", "HN", "HND", "Spanish", "es", "spa", "es-HN" },
            new string[] { "Hungary", "HU", "HUN", "Hungarian", "hu", "hun", "hu-HU" },
            new string[] { "Iceland", "IS", "ISL", "Icelandic", "is", "isl", "is-IS" },
            new string[] { "India", "IN", "IND", "Hindi", "hi", "hin", "hi-IN" },
            new string[] { "India", "IN", "IND", "Bengali", "bn", "bng", "bn-IN" },
            new string[] { "India", "IN", "IND", "Punjabi", "pa", "pan", "pa-IN" },
            new string[] { "India", "IN", "IND", "Gujarati", "gu", "guj", "gu-IN" },
            new string[] { "India", "IN", "IND", "Oriya", "or", "ori", "or-IN" },
            new string[] { "India", "IN", "IND", "Tamil", "ta", "tam", "ta-IN" },
            new string[] { "India", "IN", "IND", "Telugu", "te", "tel", "te-IN" },
            new string[] { "India", "IN", "IND", "Kannada", "kn", "kan", "kn-IN" },
            new string[] { "India", "IN", "IND", "Malayalam", "ml", "mym", "ml-IN" },
            new string[] { "India", "IN", "IND", "Assamese", "as", "asm", "as-IN" },
            new string[] { "India", "IN", "IND", "Marathi", "mr", "mar", "mr-IN" },
            new string[] { "India", "IN", "IND", "Sanskrit", "sa", "san", "sa-IN" },
            new string[] { "India", "IN", "IND", "Konkani", "kok", "kok", "kok-IN" },
            new string[] { "India", "IN", "IND", "English", "en", "eng", "en-IN" },
            new string[] { "Indonesia", "ID", "IDN", "Indonesian", "id", "ind", "id-ID" },
            new string[] { "Iran", "IR", "IRN", "Persian", "fa", "fas", "fa-IR" },
            new string[] { "Iraq", "IQ", "IRQ", "Arabic", "ar", "ara", "ar-IQ" },
            new string[] { "Ireland", "IE", "IRL", "Irish", "ga", "gle", "ga-IE" },
            new string[] { "Ireland", "IE", "IRL", "English", "en", "eng", "en-IE" },
            new string[] { "Islamic Republic of Pakistan", "PK", "PAK", "Urdu", "ur", "urd", "ur-PK" },
            new string[] { "Israel", "IL", "ISR", "Hebrew", "he", "heb", "he-IL" },
            new string[] { "Italy", "IT", "ITA", "Italian", "it", "ita", "it-IT" },
            new string[] { "Jamaica", "JM", "JAM", "English", "en", "eng", "en-JM" },
            new string[] { "Japan", "JP", "JPN", "Japanese", "ja", "jpn", "ja-JP" },
            new string[] { "Jordan", "JO", "JOR", "Arabic", "ar", "ara", "ar-JO" },
            new string[] { "Kazakhstan", "KZ", "KAZ", "Kazakh", "kk", "kaz", "kk-KZ" },
            new string[] { "Kenya", "KE", "KEN", "Kiswahili", "sw", "swa", "sw-KE" },
            new string[] { "Korea", "KR", "KOR", "Korean", "ko", "kor", "ko-KR" },
            new string[] { "Kuwait", "KW", "KWT", "Arabic", "ar", "ara", "ar-KW" },
            new string[] { "Kyrgyzstan", "KG", "KGZ", "Kyrgyz", "ky", "kir", "ky-KG" },
            new string[] { "Lao P.D.R.", "LA", "LAO", "Lao", "lo", "lao", "lo-LA" },
            new string[] { "Latin, Algeria", "DZ", "DZA", "Tamazight", "tzm", "tzm", "tzm-Latn-DZ" },
            new string[] { "Latin, Azerbaijan", "AZ", "AZE", "Azeri", "az", "aze", "az-Latn-AZ" },
            new string[] { "Latin, Bosnia and Herzegovina", "BA", "BIH", "Croatian", "hr", "hrb", "hr-BA" },
            new string[] { "Latin, Bosnia and Herzegovina", "BA", "BIH", "Bosnian", "bs", "bsb", "bs-Latn-BA" },
            new string[] { "Latin, Bosnia and Herzegovina", "BA", "BIH", "Serbian", "sr", "srs", "sr-Latn-BA" },
            new string[] { "Latin, Canada", "CA", "CAN", "Inuktitut", "iu", "iku", "iu-Latn-CA" },
            new string[] { "Latin, Montenegro", "ME", "MNE", "Serbian", "sr", "srp", "sr-Latn-ME" },
            new string[] { "Latin, Nigeria", "NG", "NGA", "Hausa", "ha", "hau", "ha-Latn-NG" },
            new string[] { "Latin, Serbia", "RS", "SRB", "Serbian", "sr", "srp", "sr-Latn-RS" },
            new string[] { "Latin, Serbia and Montenegro (Former", "CS", "SCG", "Serbian )", "sr", "srp", "sr-Latn-CS" },
            new string[] { "Latin, Uzbekistan", "UZ", "UZB", "Uzbek", "uz", "uzb", "uz-Latn-UZ" },
            new string[] { "Latvia", "LV", "LVA", "Latvian", "lv", "lav", "lv-LV" },
            new string[] { "Lebanon", "LB", "LBN", "Arabic", "ar", "ara", "ar-LB" },
            new string[] { "Libya", "LY", "LBY", "Arabic", "ar", "ara", "ar-LY" },
            new string[] { "Liechtenstein", "LI", "LIE", "German", "de", "deu", "de-LI" },
            new string[] { "Lithuania", "LT", "LTU", "Lithuanian", "lt", "lit", "lt-LT" },
            new string[] { "Luxembourg", "LU", "LUX", "Luxembourgish", "lb", "ltz", "lb-LU" },
            new string[] { "Luxembourg", "LU", "LUX", "German", "de", "deu", "de-LU" },
            new string[] { "Luxembourg", "LU", "LUX", "French", "fr", "fra", "fr-LU" },
            new string[] { "Malaysia", "MY", "MYS", "Malay", "ms", "msa", "ms-MY" },
            new string[] { "Malaysia", "MY", "MYS", "English", "en", "eng", "en-MY" },
            new string[] { "Maldives", "MV", "MDV", "Divehi", "dv", "div", "dv-MV" },
            new string[] { "Malta", "MT", "MLT", "Maltese", "mt", "mlt", "mt-MT" },
            new string[] { "Mexico", "MX", "MEX", "Spanish", "es", "spa", "es-MX" },
            new string[] { "Mohawk", "CA", "CAN", "Mohawk", "moh", "moh", "moh-CA" },
            new string[] { "Monaco", "MC", "MCO", "French", "fr", "fra", "fr-MC" },
            new string[] { "Morocco", "MA", "MAR", "Arabic", "ar", "ara", "ar-MA" },
            new string[] { "Nepal", "NP", "NPL", "Nepali", "ne", "nep", "ne-NP" },
            new string[] { "Netherlands", "NL", "NLD", "Dutch", "nl", "nld", "nl-NL" },
            new string[] { "Netherlands", "NL", "NLD", "Frisian", "fy", "fry", "fy-NL" },
            new string[] { "New Zealand", "NZ", "NZL", "Maori", "mi", "mri", "mi-NZ" },
            new string[] { "New Zealand", "NZ", "NZL", "English", "en", "eng", "en-NZ" },
            new string[] { "Nicaragua", "NI", "NIC", "Spanish", "es", "spa", "es-NI" },
            new string[] { "Nigeria", "NG", "NGA", "Yoruba", "yo", "yor", "yo-NG" },
            new string[] { "Nigeria", "NG", "NGA", "Igbo", "ig", "ibo", "ig-NG" },
            new string[] { "Norway", "NO", "NOR", "Norwegian, Bokmål", "nb", "nob", "nb-NO" },
            new string[] { "Norway", "NO", "NOR", "Sami, Northern", "se", "sme", "se-NO" },
            new string[] { "Norway", "NO", "NOR", "Norwegian, Nynorsk", "nn", "nno", "nn-NO" },
            new string[] { "Norway", "NO", "NOR", "Sami, Lule", "smj", "smj", "smj-NO" },
            new string[] { "Norway", "NO", "NOR", "Sami, Southern", "sma", "sma", "sma-NO" },
            new string[] { "Oman", "OM", "OMN", "Arabic", "ar", "ara", "ar-OM" },
            new string[] { "Panama", "PA", "PAN", "Spanish", "es", "spa", "es-PA" },
            new string[] { "Paraguay", "PY", "PRY", "Spanish", "es", "spa", "es-PY" },
            new string[] { "Peru", "PE", "PER", "Quechua", "quz", "qup", "quz-PE" },
            new string[] { "Peru", "PE", "PER", "Spanish", "es", "spa", "es-PE" },
            new string[] { "Philippines", "PH", "PHL", "Filipino", "fil", "fil", "fil-PH" },
            new string[] { "Poland", "PL", "POL", "Polish", "pl", "pol", "pl-PL" },
            new string[] { "Portugal", "PT", "PRT", "Portuguese", "pt", "por", "pt-PT" },
            new string[] { "PRC", "CN", "CHN", "Tibetan", "bo", "bod", "bo-CN" },
            new string[] { "PRC", "CN", "CHN", "Yi", "ii", "iii", "ii-CN" },
            new string[] { "PRC", "CN", "CHN", "Uyghur", "ug", "uig", "ug-CN" },
            new string[] { "Puerto Rico", "PR", "PRI", "Spanish", "es", "spa", "es-PR" },
            new string[] { "Qatar", "QA", "QAT", "Arabic", "ar", "ara", "ar-QA" },
            new string[] { "Republic of the Philippines", "PH", "PHL", "English", "en", "eng", "en-PH" },
            new string[] { "Romania", "RO", "ROU", "Romanian", "ro", "ron", "ro-RO" },
            new string[] { "Russia", "RU", "RUS", "Russian", "ru", "rus", "ru-RU" },
            new string[] { "Russia", "RU", "RUS", "Tatar", "tt", "tat", "tt-RU" },
            new string[] { "Russia", "RU", "RUS", "Bashkir", "ba", "bak", "ba-RU" },
            new string[] { "Russia", "RU", "RUS", "Yakut", "sah", "sah", "sah-RU" },
            new string[] { "Rwanda", "RW", "RWA", "Kinyarwanda", "rw", "kin", "rw-RW" },
            new string[] { "Saudi Arabia", "SA", "SAU", "Arabic", "ar", "ara", "ar-SA" },
            new string[] { "Senegal", "SN", "SEN", "Wolof", "wo", "wol", "wo-SN" },
            new string[] { "Simplified, PRC", "CN", "CHN", "Chinese", "zh", "zho", "zh-CN" },
            new string[] { "Simplified, Singapore", "SG", "SGP", "Chinese", "zh", "zho", "zh-SG" },
            new string[] { "Singapore", "SG", "SGP", "English", "en", "eng", "en-SG" },
            new string[] { "Slovakia", "SK", "SVK", "Slovak", "sk", "slk", "sk-SK" },
            new string[] { "Slovenia", "SI", "SVN", "Slovenian", "sl", "slv", "sl-SI" },
            new string[] { "South Africa", "ZA", "ZAF", "Setswana", "tn", "tsn", "tn-ZA" },
            new string[] { "South Africa", "ZA", "ZAF", "isiXhosa", "xh", "xho", "xh-ZA" },
            new string[] { "South Africa", "ZA", "ZAF", "isiZulu", "zu", "zul", "zu-ZA" },
            new string[] { "South Africa", "ZA", "ZAF", "Afrikaans", "af", "afr", "af-ZA" },
            new string[] { "South Africa", "ZA", "ZAF", "Sesotho sa Leboa", "nso", "nso", "nso-ZA" },
            new string[] { "South Africa", "ZA", "ZAF", "English", "en", "eng", "en-ZA" },
            new string[] { "Spain, International Sort", "ES", "ESP", "Spanish", "es", "spa", "es-ES" },
            new string[] { "Sri Lanka", "LK", "LKA", "Sinhala", "si", "sin", "si-LK" },
            new string[] { "Sweden", "SE", "SWE", "Swedish", "sv", "swe", "sv-SE" },
            new string[] { "Sweden", "SE", "SWE", "Sami, Northern", "se", "smf", "se-SE" },
            new string[] { "Sweden", "SE", "SWE", "Sami, Lule", "smj", "smk", "smj-SE" },
            new string[] { "Sweden", "SE", "SWE", "Sami, Southern", "sma", "smb", "sma-SE" },
            new string[] { "Switzerland", "CH", "CHE", "Romansh", "rm", "roh", "rm-CH" },
            new string[] { "Switzerland", "CH", "CHE", "German", "de", "deu", "de-CH" },
            new string[] { "Switzerland", "CH", "CHE", "Italian", "it", "ita", "it-CH" },
            new string[] { "Switzerland", "CH", "CHE", "French", "fr", "fra", "fr-CH" },
            new string[] { "Syllabics, Canada", "CA", "CAN", "Inuktitut", "iu", "iku", "iu-Cans-CA" },
            new string[] { "Syria", "SY", "SYR", "Syriac", "syr", "syr", "syr-SY" },
            new string[] { "Syria", "SY", "SYR", "Arabic", "ar", "ara", "ar-SY" },
            new string[] { "Thailand", "TH", "THA", "Thai", "th", "tha", "th-TH" },
            new string[] { "Traditional Mongolian, PRC", "CN", "CHN", "Mongolian", "mn", "mon", "mn-Mong-CN" },
            new string[] { "Traditional, Hong Kong S.A.R.", "HK", "HKG", "Chinese", "zh", "zho", "zh-HK" },
            new string[] { "Traditional, Macao S.A.R.", "MO", "MAC", "Chinese", "zh", "zho", "zh-MO" },
            new string[] { "Traditional, Taiwan", "TW", "TWN", "Chinese", "zh", "zho", "zh-TW" },
            new string[] { "Trinidad and Tobago", "TT", "TTO", "English", "en", "eng", "en-TT" },
            new string[] { "Tunisia", "TN", "TUN", "Arabic", "ar", "ara", "ar-TN" },
            new string[] { "Turkey", "TR", "TUR", "Turkish", "tr", "tur", "tr-TR" },
            new string[] { "Turkmenistan", "TM", "TKM", "Turkmen", "tk", "tuk", "tk-TM" },
            new string[] { "U.A.E.", "AE", "ARE", "Arabic", "ar", "ara", "ar-AE" },
            new string[] { "Ukraine", "UA", "UKR", "Ukrainian", "uk", "ukr", "uk-UA" },
            new string[] { "United Kingdom", "GB", "GBR", "Welsh", "cy", "cym", "cy-GB" },
            new string[] { "United Kingdom", "GB", "GBR", "Scottish Gaelic", "gd", "gla", "gd-GB" },
            new string[] { "United Kingdom", "GB", "GBR", "English", "en", "eng", "en-GB" },
            new string[] { "United States", "US", "USA", "English", "en", "eng", "en-US" },
            new string[] { "United States", "US", "USA", "Spanish", "es", "spa", "es-US" },
            new string[] { "Uruguay", "UY", "URY", "Spanish", "es", "spa", "es-UY" },
            new string[] { "Vietnam", "VN", "VNM", "Vietnamese", "vi", "vie", "vi-VN" },
            new string[] { "Yemen", "YE", "YEM", "Arabic", "ar", "ara", "ar-YE" },
            new string[] { "Zimbabwe", "ZW", "ZWE", "English", "en", "eng", "en-ZW" }
        };

        // GET view
        [HttpGet]
        [Route("test")]
        public IActionResult Test()
        {
            ViewBag.Locales = Locales;

            return View();
        }
    }
}
