package main

import "net/http"

import "github.com/gin-gonic/gin"

func main() {
	Locales := [][]string{
		[]string{"Afghanistan", "AF", "AFG", "Pashto", "ps", "pus", "ps-AF"},
		[]string{"Afghanistan", "AF", "AFG", "Dari", "prs", "prs", "prs-AF"},
		[]string{"Albania", "AL", "ALB", "Albanian", "sq", "sqi", "sq-AL"},
		[]string{"Algeria", "DZ", "DZA", "Arabic", "ar", "ara", "ar-DZ"},
		[]string{"Argentina", "AR", "ARG", "Spanish", "es", "spa", "es-AR"},
		[]string{"Armenia", "AM", "ARM", "Armenian", "hy", "hye", "hy-AM"},
		[]string{"Australia", "AU", "AUS", "English", "en", "eng", "en-AU"},
		[]string{"Austria", "AT", "AUT", "German", "de", "deu", "de-AT"},
		[]string{"Bahrain", "BH", "BHR", "Arabic", "ar", "ara", "ar-BH"},
		[]string{"Bangladesh", "BD", "BGD", "Bengali", "bn", "bng", "bn-BD"},
		[]string{"Basque", "ES", "ESP", "Basque", "eu", "eus", "eu-ES"},
		[]string{"Belarus", "BY", "BLR", "Belarusian", "be", "bel", "be-BY"},
		[]string{"Belgium", "BE", "BEL", "French", "fr", "fra", "fr-BE"},
		[]string{"Belgium", "BE", "BEL", "Dutch", "nl", "nld", "nl-BE"},
		[]string{"Belize", "BZ", "BLZ", "English", "en", "eng", "en-BZ"},
		[]string{"Bolivarian Republic of Venezuela", "VE", "VEN", "Spanish", "es", "spa", "es-VE"},
		[]string{"Bolivia", "BO", "BOL", "Quechua", "quz", "qub", "quz-BO"},
		[]string{"Bolivia", "BO", "BOL", "Spanish", "es", "spa", "es-BO"},
		[]string{"Brazil", "BR", "BRA", "Portuguese", "pt", "por", "pt-BR"},
		[]string{"Brunei Darussalam", "BN", "BRN", "Malay", "ms", "msa", "ms-BN"},
		[]string{"Bulgaria", "BG", "BGR", "Bulgarian", "bg", "bul", "bg-BG"},
		[]string{"Cambodia", "KH", "KHM", "Khmer", "km", "khm", "km-KH"},
		[]string{"Canada", "CA", "CAN", "French", "fr", "fra", "fr-CA"},
		[]string{"Canada", "CA", "CAN", "English", "en", "eng", "en-CA"},
		[]string{"Caribbean", "29", "29", "English", "en", "eng", "en-029"},
		[]string{"Catalan", "ES", "ESP", "Catalan", "ca", "cat", "ca-ES"},
		[]string{"Chile", "CL", "CHL", "Mapudungun", "arn", "arn", "arn-CL"},
		[]string{"Chile", "CL", "CHL", "Spanish", "es", "spa", "es-CL"},
		[]string{"Colombia", "CO", "COL", "Spanish", "es", "spa", "es-CO"},
		[]string{"Costa Rica", "CR", "CRI", "Spanish", "es", "spa", "es-CR"},
		[]string{"Croatia", "HR", "HRV", "Croatian", "hr", "hrv", "hr-HR"},
		[]string{"Cyrillic, Azerbaijan", "AZ", "AZE", "Azeri", "az", "aze", "az-Cyrl-AZ"},
		[]string{"Cyrillic, Bosnia and Herzegovina", "BA", "BIH", "Serbian", "sr", "srn", "sr-Cyrl-BA"},
		[]string{"Cyrillic, Bosnia and Herzegovina", "BA", "BIH", "Bosnian", "bs", "bsc", "bs-Cyrl-BA"},
		[]string{"Cyrillic, Mongolia", "MN", "MNG", "Mongolian", "mn", "mon", "mn-MN"},
		[]string{"Cyrillic, Montenegro", "ME", "MNE", "Serbian", "sr", "srp", "sr-Cyrl-ME"},
		[]string{"Cyrillic, Serbia", "RS", "SRB", "Serbian", "sr", "srp", "sr-Cyrl-RS"},
		[]string{"Cyrillic, Serbia and Montenegro (Former", "CS", "SCG", "Serbian )", "sr", "srp", "sr-Cyrl-CS"},
		[]string{"Cyrillic, Tajikistan", "TJ", "TAJ", "Tajik", "tg", "tgk", "tg-Cyrl-TJ"},
		[]string{"Cyrillic, Uzbekistan", "UZ", "UZB", "Uzbek", "uz", "uzb", "uz-Cyrl-UZ"},
		[]string{"Czech Republic", "CZ", "CZE", "Czech", "cs", "ces", "cs-CZ"},
		[]string{"Denmark", "DK", "DNK", "Danish", "da", "dan", "da-DK"},
		[]string{"Dominican Republic", "DO", "DOM", "Spanish", "es", "spa", "es-DO"},
		[]string{"Ecuador", "EC", "ECU", "Quechua", "quz", "que", "quz-EC"},
		[]string{"Ecuador", "EC", "ECU", "Spanish", "es", "spa", "es-EC"},
		[]string{"Egypt", "EG", "EGY", "Arabic", "ar", "ara", "ar-EG"},
		[]string{"El Salvador", "SV", "SLV", "Spanish", "es", "spa", "es-SV"},
		[]string{"Estonia", "EE", "EST", "Estonian", "et", "est", "et-EE"},
		[]string{"Ethiopia", "ET", "ETH", "Amharic", "am", "amh", "am-ET"},
		[]string{"Faroe Islands", "FO", "FRO", "Faroese", "fo", "fao", "fo-FO"},
		[]string{"Finland", "FI", "FIN", "Finnish", "fi", "fin", "fi-FI"},
		[]string{"Finland", "FI", "FIN", "Swedish", "sv", "swe", "sv-FI"},
		[]string{"Finland", "FI", "FIN", "Sami, Northern", "se", "smg", "se-FI"},
		[]string{"Finland", "FI", "FIN", "Sami, Skolt", "sms", "sms", "sms-FI"},
		[]string{"Finland", "FI", "FIN", "Sami, Inari", "smn", "smn", "smn-FI"},
		[]string{"Former Yugoslav Republic of Macedonia", "MK", "MKD", "Macedonian", "mk", "mkd", "mk-MK"},
		[]string{"France", "FR", "FRA", "French", "fr", "fra", "fr-FR"},
		[]string{"France", "FR", "FRA", "Breton", "br", "bre", "br-FR"},
		[]string{"France", "FR", "FRA", "Occitan", "oc", "oci", "oc-FR"},
		[]string{"France", "FR", "FRA", "Corsican", "co", "cos", "co-FR"},
		[]string{"France", "FR", "FRA", "Alsatian", "gsw", "gsw", "gsw-FR"},
		[]string{"Galician", "ES", "ESP", "Galician", "gl", "glg", "gl-ES"},
		[]string{"Georgia", "GE", "GEO", "Georgian", "ka", "kat", "ka-GE"},
		[]string{"Germany", "DE", "DEU", "German", "de", "deu", "de-DE"},
		[]string{"Germany", "DE", "DEU", "Upper Sorbian", "hsb", "hsb", "hsb-DE"},
		[]string{"Germany", "DE", "DEU", "Lower Sorbian", "dsb", "dsb", "dsb-DE"},
		[]string{"Greece", "GR", "GRC", "Greek", "el", "ell", "el-GR"},
		[]string{"Greenland", "GL", "GRL", "Greenlandic", "kl", "kal", "kl-GL"},
		[]string{"Guatemala", "GT", "GTM", "K'iche", "qut", "qut", "qut-GT"},
		[]string{"Guatemala", "GT", "GTM", "Spanish", "es", "spa", "es-GT"},
		[]string{"Honduras", "HN", "HND", "Spanish", "es", "spa", "es-HN"},
		[]string{"Hungary", "HU", "HUN", "Hungarian", "hu", "hun", "hu-HU"},
		[]string{"Iceland", "IS", "ISL", "Icelandic", "is", "isl", "is-IS"},
		[]string{"India", "IN", "IND", "Hindi", "hi", "hin", "hi-IN"},
		[]string{"India", "IN", "IND", "Bengali", "bn", "bng", "bn-IN"},
		[]string{"India", "IN", "IND", "Punjabi", "pa", "pan", "pa-IN"},
		[]string{"India", "IN", "IND", "Gujarati", "gu", "guj", "gu-IN"},
		[]string{"India", "IN", "IND", "Oriya", "or", "ori", "or-IN"},
		[]string{"India", "IN", "IND", "Tamil", "ta", "tam", "ta-IN"},
		[]string{"India", "IN", "IND", "Telugu", "te", "tel", "te-IN"},
		[]string{"India", "IN", "IND", "Kannada", "kn", "kan", "kn-IN"},
		[]string{"India", "IN", "IND", "Malayalam", "ml", "mym", "ml-IN"},
		[]string{"India", "IN", "IND", "Assamese", "as", "asm", "as-IN"},
		[]string{"India", "IN", "IND", "Marathi", "mr", "mar", "mr-IN"},
		[]string{"India", "IN", "IND", "Sanskrit", "sa", "san", "sa-IN"},
		[]string{"India", "IN", "IND", "Konkani", "kok", "kok", "kok-IN"},
		[]string{"India", "IN", "IND", "English", "en", "eng", "en-IN"},
		[]string{"Indonesia", "ID", "IDN", "Indonesian", "id", "ind", "id-ID"},
		[]string{"Iran", "IR", "IRN", "Persian", "fa", "fas", "fa-IR"},
		[]string{"Iraq", "IQ", "IRQ", "Arabic", "ar", "ara", "ar-IQ"},
		[]string{"Ireland", "IE", "IRL", "Irish", "ga", "gle", "ga-IE"},
		[]string{"Ireland", "IE", "IRL", "English", "en", "eng", "en-IE"},
		[]string{"Islamic Republic of Pakistan", "PK", "PAK", "Urdu", "ur", "urd", "ur-PK"},
		[]string{"Israel", "IL", "ISR", "Hebrew", "he", "heb", "he-IL"},
		[]string{"Italy", "IT", "ITA", "Italian", "it", "ita", "it-IT"},
		[]string{"Jamaica", "JM", "JAM", "English", "en", "eng", "en-JM"},
		[]string{"Japan", "JP", "JPN", "Japanese", "ja", "jpn", "ja-JP"},
		[]string{"Jordan", "JO", "JOR", "Arabic", "ar", "ara", "ar-JO"},
		[]string{"Kazakhstan", "KZ", "KAZ", "Kazakh", "kk", "kaz", "kk-KZ"},
		[]string{"Kenya", "KE", "KEN", "Kiswahili", "sw", "swa", "sw-KE"},
		[]string{"Korea", "KR", "KOR", "Korean", "ko", "kor", "ko-KR"},
		[]string{"Kuwait", "KW", "KWT", "Arabic", "ar", "ara", "ar-KW"},
		[]string{"Kyrgyzstan", "KG", "KGZ", "Kyrgyz", "ky", "kir", "ky-KG"},
		[]string{"Lao P.D.R.", "LA", "LAO", "Lao", "lo", "lao", "lo-LA"},
		[]string{"Latin, Algeria", "DZ", "DZA", "Tamazight", "tzm", "tzm", "tzm-Latn-DZ"},
		[]string{"Latin, Azerbaijan", "AZ", "AZE", "Azeri", "az", "aze", "az-Latn-AZ"},
		[]string{"Latin, Bosnia and Herzegovina", "BA", "BIH", "Croatian", "hr", "hrb", "hr-BA"},
		[]string{"Latin, Bosnia and Herzegovina", "BA", "BIH", "Bosnian", "bs", "bsb", "bs-Latn-BA"},
		[]string{"Latin, Bosnia and Herzegovina", "BA", "BIH", "Serbian", "sr", "srs", "sr-Latn-BA"},
		[]string{"Latin, Canada", "CA", "CAN", "Inuktitut", "iu", "iku", "iu-Latn-CA"},
		[]string{"Latin, Montenegro", "ME", "MNE", "Serbian", "sr", "srp", "sr-Latn-ME"},
		[]string{"Latin, Nigeria", "NG", "NGA", "Hausa", "ha", "hau", "ha-Latn-NG"},
		[]string{"Latin, Serbia", "RS", "SRB", "Serbian", "sr", "srp", "sr-Latn-RS"},
		[]string{"Latin, Serbia and Montenegro (Former", "CS", "SCG", "Serbian )", "sr", "srp", "sr-Latn-CS"},
		[]string{"Latin, Uzbekistan", "UZ", "UZB", "Uzbek", "uz", "uzb", "uz-Latn-UZ"},
		[]string{"Latvia", "LV", "LVA", "Latvian", "lv", "lav", "lv-LV"},
		[]string{"Lebanon", "LB", "LBN", "Arabic", "ar", "ara", "ar-LB"},
		[]string{"Libya", "LY", "LBY", "Arabic", "ar", "ara", "ar-LY"},
		[]string{"Liechtenstein", "LI", "LIE", "German", "de", "deu", "de-LI"},
		[]string{"Lithuania", "LT", "LTU", "Lithuanian", "lt", "lit", "lt-LT"},
		[]string{"Luxembourg", "LU", "LUX", "Luxembourgish", "lb", "ltz", "lb-LU"},
		[]string{"Luxembourg", "LU", "LUX", "German", "de", "deu", "de-LU"},
		[]string{"Luxembourg", "LU", "LUX", "French", "fr", "fra", "fr-LU"},
		[]string{"Malaysia", "MY", "MYS", "Malay", "ms", "msa", "ms-MY"},
		[]string{"Malaysia", "MY", "MYS", "English", "en", "eng", "en-MY"},
		[]string{"Maldives", "MV", "MDV", "Divehi", "dv", "div", "dv-MV"},
		[]string{"Malta", "MT", "MLT", "Maltese", "mt", "mlt", "mt-MT"},
		[]string{"Mexico", "MX", "MEX", "Spanish", "es", "spa", "es-MX"},
		[]string{"Mohawk", "CA", "CAN", "Mohawk", "moh", "moh", "moh-CA"},
		[]string{"Monaco", "MC", "MCO", "French", "fr", "fra", "fr-MC"},
		[]string{"Morocco", "MA", "MAR", "Arabic", "ar", "ara", "ar-MA"},
		[]string{"Nepal", "NP", "NPL", "Nepali", "ne", "nep", "ne-NP"},
		[]string{"Netherlands", "NL", "NLD", "Dutch", "nl", "nld", "nl-NL"},
		[]string{"Netherlands", "NL", "NLD", "Frisian", "fy", "fry", "fy-NL"},
		[]string{"New Zealand", "NZ", "NZL", "Maori", "mi", "mri", "mi-NZ"},
		[]string{"New Zealand", "NZ", "NZL", "English", "en", "eng", "en-NZ"},
		[]string{"Nicaragua", "NI", "NIC", "Spanish", "es", "spa", "es-NI"},
		[]string{"Nigeria", "NG", "NGA", "Yoruba", "yo", "yor", "yo-NG"},
		[]string{"Nigeria", "NG", "NGA", "Igbo", "ig", "ibo", "ig-NG"},
		[]string{"Norway", "NO", "NOR", "Norwegian, Bokmål", "nb", "nob", "nb-NO"},
		[]string{"Norway", "NO", "NOR", "Sami, Northern", "se", "sme", "se-NO"},
		[]string{"Norway", "NO", "NOR", "Norwegian, Nynorsk", "nn", "nno", "nn-NO"},
		[]string{"Norway", "NO", "NOR", "Sami, Lule", "smj", "smj", "smj-NO"},
		[]string{"Norway", "NO", "NOR", "Sami, Southern", "sma", "sma", "sma-NO"},
		[]string{"Oman", "OM", "OMN", "Arabic", "ar", "ara", "ar-OM"},
		[]string{"Panama", "PA", "PAN", "Spanish", "es", "spa", "es-PA"},
		[]string{"Paraguay", "PY", "PRY", "Spanish", "es", "spa", "es-PY"},
		[]string{"Peru", "PE", "PER", "Quechua", "quz", "qup", "quz-PE"},
		[]string{"Peru", "PE", "PER", "Spanish", "es", "spa", "es-PE"},
		[]string{"Philippines", "PH", "PHL", "Filipino", "fil", "fil", "fil-PH"},
		[]string{"Poland", "PL", "POL", "Polish", "pl", "pol", "pl-PL"},
		[]string{"Portugal", "PT", "PRT", "Portuguese", "pt", "por", "pt-PT"},
		[]string{"PRC", "CN", "CHN", "Tibetan", "bo", "bod", "bo-CN"},
		[]string{"PRC", "CN", "CHN", "Yi", "ii", "iii", "ii-CN"},
		[]string{"PRC", "CN", "CHN", "Uyghur", "ug", "uig", "ug-CN"},
		[]string{"Puerto Rico", "PR", "PRI", "Spanish", "es", "spa", "es-PR"},
		[]string{"Qatar", "QA", "QAT", "Arabic", "ar", "ara", "ar-QA"},
		[]string{"Republic of the Philippines", "PH", "PHL", "English", "en", "eng", "en-PH"},
		[]string{"Romania", "RO", "ROU", "Romanian", "ro", "ron", "ro-RO"},
		[]string{"Russia", "RU", "RUS", "Russian", "ru", "rus", "ru-RU"},
		[]string{"Russia", "RU", "RUS", "Tatar", "tt", "tat", "tt-RU"},
		[]string{"Russia", "RU", "RUS", "Bashkir", "ba", "bak", "ba-RU"},
		[]string{"Russia", "RU", "RUS", "Yakut", "sah", "sah", "sah-RU"},
		[]string{"Rwanda", "RW", "RWA", "Kinyarwanda", "rw", "kin", "rw-RW"},
		[]string{"Saudi Arabia", "SA", "SAU", "Arabic", "ar", "ara", "ar-SA"},
		[]string{"Senegal", "SN", "SEN", "Wolof", "wo", "wol", "wo-SN"},
		[]string{"Simplified, PRC", "CN", "CHN", "Chinese", "zh", "zho", "zh-CN"},
		[]string{"Simplified, Singapore", "SG", "SGP", "Chinese", "zh", "zho", "zh-SG"},
		[]string{"Singapore", "SG", "SGP", "English", "en", "eng", "en-SG"},
		[]string{"Slovakia", "SK", "SVK", "Slovak", "sk", "slk", "sk-SK"},
		[]string{"Slovenia", "SI", "SVN", "Slovenian", "sl", "slv", "sl-SI"},
		[]string{"South Africa", "ZA", "ZAF", "Setswana", "tn", "tsn", "tn-ZA"},
		[]string{"South Africa", "ZA", "ZAF", "isiXhosa", "xh", "xho", "xh-ZA"},
		[]string{"South Africa", "ZA", "ZAF", "isiZulu", "zu", "zul", "zu-ZA"},
		[]string{"South Africa", "ZA", "ZAF", "Afrikaans", "af", "afr", "af-ZA"},
		[]string{"South Africa", "ZA", "ZAF", "Sesotho sa Leboa", "nso", "nso", "nso-ZA"},
		[]string{"South Africa", "ZA", "ZAF", "English", "en", "eng", "en-ZA"},
		[]string{"Spain, International Sort", "ES", "ESP", "Spanish", "es", "spa", "es-ES"},
		[]string{"Sri Lanka", "LK", "LKA", "Sinhala", "si", "sin", "si-LK"},
		[]string{"Sweden", "SE", "SWE", "Swedish", "sv", "swe", "sv-SE"},
		[]string{"Sweden", "SE", "SWE", "Sami, Northern", "se", "smf", "se-SE"},
		[]string{"Sweden", "SE", "SWE", "Sami, Lule", "smj", "smk", "smj-SE"},
		[]string{"Sweden", "SE", "SWE", "Sami, Southern", "sma", "smb", "sma-SE"},
		[]string{"Switzerland", "CH", "CHE", "Romansh", "rm", "roh", "rm-CH"},
		[]string{"Switzerland", "CH", "CHE", "German", "de", "deu", "de-CH"},
		[]string{"Switzerland", "CH", "CHE", "Italian", "it", "ita", "it-CH"},
		[]string{"Switzerland", "CH", "CHE", "French", "fr", "fra", "fr-CH"},
		[]string{"Syllabics, Canada", "CA", "CAN", "Inuktitut", "iu", "iku", "iu-Cans-CA"},
		[]string{"Syria", "SY", "SYR", "Syriac", "syr", "syr", "syr-SY"},
		[]string{"Syria", "SY", "SYR", "Arabic", "ar", "ara", "ar-SY"},
		[]string{"Thailand", "TH", "THA", "Thai", "th", "tha", "th-TH"},
		[]string{"Traditional Mongolian, PRC", "CN", "CHN", "Mongolian", "mn", "mon", "mn-Mong-CN"},
		[]string{"Traditional, Hong Kong S.A.R.", "HK", "HKG", "Chinese", "zh", "zho", "zh-HK"},
		[]string{"Traditional, Macao S.A.R.", "MO", "MAC", "Chinese", "zh", "zho", "zh-MO"},
		[]string{"Traditional, Taiwan", "TW", "TWN", "Chinese", "zh", "zho", "zh-TW"},
		[]string{"Trinidad and Tobago", "TT", "TTO", "English", "en", "eng", "en-TT"},
		[]string{"Tunisia", "TN", "TUN", "Arabic", "ar", "ara", "ar-TN"},
		[]string{"Turkey", "TR", "TUR", "Turkish", "tr", "tur", "tr-TR"},
		[]string{"Turkmenistan", "TM", "TKM", "Turkmen", "tk", "tuk", "tk-TM"},
		[]string{"U.A.E.", "AE", "ARE", "Arabic", "ar", "ara", "ar-AE"},
		[]string{"Ukraine", "UA", "UKR", "Ukrainian", "uk", "ukr", "uk-UA"},
		[]string{"United Kingdom", "GB", "GBR", "Welsh", "cy", "cym", "cy-GB"},
		[]string{"United Kingdom", "GB", "GBR", "Scottish Gaelic", "gd", "gla", "gd-GB"},
		[]string{"United Kingdom", "GB", "GBR", "English", "en", "eng", "en-GB"},
		[]string{"United States", "US", "USA", "English", "en", "eng", "en-US"},
		[]string{"United States", "US", "USA", "Spanish", "es", "spa", "es-US"},
		[]string{"Uruguay", "UY", "URY", "Spanish", "es", "spa", "es-UY"},
		[]string{"Vietnam", "VN", "VNM", "Vietnamese", "vi", "vie", "vi-VN"},
		[]string{"Yemen", "YE", "YEM", "Arabic", "ar", "ara", "ar-YE"},
		[]string{"Zimbabwe", "ZW", "ZWE", "English", "en", "eng", "en-ZW"},
	}

	gin.SetMode(gin.ReleaseMode)

	router := gin.New()

	router.LoadHTMLGlob("templates/*")

	router.GET("/api/json", func(ctx *gin.Context) {
		ctx.JSON(http.StatusOK, []string{"value1", "value2"})
	})

	router.GET("/view/test", func(ctx *gin.Context) {
		ctx.HTML(http.StatusOK, "test.tpl", gin.H{
			"Locales": Locales,
		})
	})

	router.Run(":9000")
}
